import type { EnterprisePageContent } from './SolutionEnterpriseTemplate'

export const solutionEnterpriseContent: Record<string, EnterprisePageContent> = {
  'formedrix-lims': {
    title: 'ForMedrix LIMS',
    subtitle: 'A single-platform laboratory operations system supporting the full specimen journey from order to release with strong governance and quality control.',
    heroImageUrl: 'https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Technological Excellence for Core Lab Operations',
    overviewText: 'ForMedrix LIMS is built for modern pathology organizations that need consistent workflows, traceability, and high throughput across sites and specialties.',
    valuePoints: ['Specimen journey orchestration', 'Multi-discipline workflow templates', 'Role-based release control', 'Audit-ready data lineage'],
    solutionPillars: [
      { title: 'Integrated Systems for Modern Organizations', description: 'Connect order entry, instrumentation, validation, and reporting into one governed flow.' },
      { title: 'Working in Partnership', description: 'Deployment is delivered through phased planning, stakeholder alignment, and measurable adoption milestones.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Secure controls and resilient architecture designed for scalability and regulatory alignment.' },
    ],
    implementationSteps: ['Current-state workflow discovery', 'Configuration and interoperability setup', 'Pilot validation and quality sign-off', 'Production rollout with KPI tracking'],
    securityAndScale: ['Role-based access and policy guardrails', 'Immutable audit logs', 'Resilient high-availability deployment'],
    faqs: [
      { question: 'Can ForMedrix LIMS replace legacy systems gradually?', answer: 'Yes, phased deployment supports coexistence while sites transition to standardized workflows.' },
      { question: 'Does it support multi-site operations?', answer: 'Yes, common governance with local operational flexibility is supported out of the box.' },
    ],
    ctaLabel: 'Request LIMS Assessment',
  },
  'predictive-analytics': {
    title: 'Predictive Analytics',
    subtitle: 'Clinical operations forecasting for workload, turnaround risk, and resource optimization across diagnostic services.',
    heroImageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Comprehensive Analytics Enhancing Service Reliability',
    overviewText: 'This solution turns historical and live laboratory signals into operational forecasts that help teams prevent delays and manage demand with confidence.',
    valuePoints: ['Demand forecasting models', 'Backlog risk prediction', 'Shift-level staffing intelligence', 'Consumable requirement projection'],
    solutionPillars: [
      { title: 'Integrated Planning Signals', description: 'Forecasting combines order trends, test complexity, and instrument capacity for practical daily planning.' },
      { title: 'Working in Partnership', description: 'Teams co-design KPI baselines and alert thresholds to match local operating realities.' },
      { title: 'Speaking Your Language', description: 'Planning outputs are aligned to lab manager decisions, not data science-only metrics.' },
    ],
    implementationSteps: ['KPI baseline and data quality review', 'Model calibration by department', 'Threshold tuning with operations leads', 'Continuous optimization after go-live'],
    securityAndScale: ['Controlled access to planning dashboards', 'Department-level visibility permissions', 'Scalable analytics compute by load profile'],
    faqs: [
      { question: 'How quickly can forecasting become reliable?', answer: 'Most labs see stable operational forecasts after calibration cycles using 8-12 weeks of quality data.' },
      { question: 'Can each department have separate thresholds?', answer: 'Yes, alerting and forecast sensitivity are configurable by discipline and site.' },
    ],
    ctaLabel: 'Book Forecasting Session',
  },
  'real-time-diagnostics': {
    title: 'Real-Time Diagnostics',
    subtitle: 'Priority-aware diagnostic workflow support to accelerate review and escalation for clinically urgent cases.',
    heroImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1581595219315-a187dd40c322?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Rapid Diagnostic Response with Clinical Confidence',
    overviewText: 'Real-Time Diagnostics helps teams identify critical samples early and route them through fast-lane validation and review paths.',
    valuePoints: ['Critical-case triage engine', 'Live signal monitoring', 'Escalation workflow automation', 'Priority queue supervision'],
    solutionPillars: [
      { title: 'Integrated Acute-Care Workflows', description: 'Urgent testing queues are coordinated with review and release checkpoints in real time.' },
      { title: 'Working in Partnership', description: 'Clinical leadership and lab operations jointly define escalation and intervention criteria.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Resilient systems protect continuity where every minute matters in care delivery.' },
    ],
    implementationSteps: ['Critical workflow mapping', 'Alert rule configuration', 'Pilot in selected urgent pathways', 'Scale-out across priority testing services'],
    securityAndScale: ['Operational alert auditability', 'Role-based critical queue access', 'High-availability event processing'],
    faqs: [
      { question: 'Does this replace clinician judgment?', answer: 'No, it accelerates prioritization while final interpretation remains clinician-led.' },
      { question: 'Can we set escalation by test type?', answer: 'Yes, escalation logic is configurable by assay, service line, and urgency level.' },
    ],
    ctaLabel: 'Discuss Critical Workflow Design',
  },
  'disease-surveillance': {
    title: 'Disease Surveillance',
    subtitle: 'Regional and network-wide intelligence for epidemiology programs requiring timely trend detection and coordinated action.',
    heroImageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1579154341098-e4e158cc7f55?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1579684453423-f84349ef60b0?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Public Health Surveillance with Operational Clarity',
    overviewText: 'The platform aggregates distributed diagnostics data, normalizes it, and presents actionable trend and risk insights to surveillance teams.',
    valuePoints: ['Trend and anomaly detection', 'Regional risk dashboards', 'Policy-based alert routing', 'Program-level reporting automation'],
    solutionPillars: [
      { title: 'Integrated Systems for Program Networks', description: 'Connect multiple reporting entities into a single surveillance intelligence view.' },
      { title: 'Speaking Your Language', description: 'Outputs are aligned to epidemiology and public program response structures.' },
      { title: 'Working in Partnership', description: 'Threshold and intervention models are co-designed with program stakeholders.' },
    ],
    implementationSteps: ['Source and governance mapping', 'Data harmonization setup', 'Alert and dashboard validation', 'Program rollout and review cadence'],
    securityAndScale: ['Controlled access by geography and role', 'Policy-compliant data sharing', 'Scalable analytics for outbreak periods'],
    faqs: [
      { question: 'Can surveillance be segmented by region and cohort?', answer: 'Yes, segmentation supports geography, population group, and temporal filters.' },
      { question: 'Is automated reporting available?', answer: 'Yes, scheduled and event-based reporting workflows are supported.' },
    ],
    ctaLabel: 'Plan Surveillance Deployment',
  },
  'quality-intelligence': {
    title: 'Quality Intelligence',
    subtitle: 'Continuous QA/QC intelligence to detect drift, reduce repeat nonconformance, and improve audit readiness.',
    heroImageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1580281658629-2f4a10e61d9d?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Proven Capability to Build Efficient Quality Processes',
    overviewText: 'Quality Intelligence enables laboratories to shift from periodic review to proactive quality governance with operational visibility.',
    valuePoints: ['Drift and exception detection', 'CAPA monitoring workflows', 'Control chart intelligence', 'Inspection evidence readiness'],
    solutionPillars: [
      { title: 'Integrated Quality Supervision', description: 'Quality events, controls, and actions are tracked in one operational model.' },
      { title: 'Working in Partnership', description: 'Quality and operational teams define thresholds and corrective action pathways together.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Evidence and quality history remain secure, traceable, and inspection-ready.' },
    ],
    implementationSteps: ['Control framework setup', 'Exception classification model', 'CAPA lifecycle rollout', 'Quality KPI governance cadence'],
    securityAndScale: ['Evidence history integrity', 'Role-based corrective action access', 'Cross-site quality benchmarking support'],
    faqs: [
      { question: 'Can CAPA status be tracked enterprise-wide?', answer: 'Yes, CAPA workflows support local and corporate-level governance visibility.' },
      { question: 'Does this support accreditation audits?', answer: 'Yes, audit packets and quality history are available through controlled exports.' },
    ],
    ctaLabel: 'Start Quality Program Review',
  },
  'data-integration-hub': {
    title: 'Data Integration Hub',
    subtitle: 'Interoperability framework for LIS, EHR, instruments, and partner ecosystems with robust governance and observability.',
    heroImageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1504814532849-cff240bbc503?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Market-Leading Interoperability for Modern Diagnostics',
    overviewText: 'The Data Integration Hub reduces technical fragmentation by standardizing connectivity, mapping, and monitoring across systems.',
    valuePoints: ['HL7/FHIR and API connectors', 'Message transformation templates', 'Integration observability', 'Retry and exception handling'],
    solutionPillars: [
      { title: 'Integrated Systems for Modern Organizations', description: 'Bridge core healthcare and diagnostics systems with governed exchange patterns.' },
      { title: 'Working in Partnership', description: 'Interface plans are phased to reduce operational risk during migration and expansion.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Secure integration architecture supports resilience and long-term scalability.' },
    ],
    implementationSteps: ['Interface inventory and priority mapping', 'Connector deployment and transformations', 'Validation and partner testing', 'Production cutover and monitoring'],
    securityAndScale: ['Secure message transport controls', 'Role-scoped integration administration', 'Scalable processing for variable loads'],
    faqs: [
      { question: 'Can legacy systems be integrated?', answer: 'Yes, adapter-based integration supports legacy and modern endpoints.' },
      { question: 'How are failed messages handled?', answer: 'Retry, dead-letter routing, and traceability are built into the integration pipeline.' },
    ],
    ctaLabel: 'Assess Integration Landscape',
  },
  'compliance-automation': {
    title: 'Compliance Automation',
    subtitle: 'Policy-driven compliance operations for laboratory environments with strict regulatory and governance requirements.',
    heroImageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Regulatory Confidence Through Automation',
    overviewText: 'Compliance Automation standardizes control execution, evidence capture, and audit preparation across quality and risk programs.',
    valuePoints: ['Policy enforcement workflows', 'Evidence lifecycle tracking', 'Inspection readiness dashboards', 'Control exception management'],
    solutionPillars: [
      { title: 'Integrated Governance by Design', description: 'Compliance controls are embedded in operational processes, not managed offline.' },
      { title: 'Working in Partnership', description: 'Governance and operations teams align on practical controls and review cycles.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Security and traceability guardrails protect evidence integrity at scale.' },
    ],
    implementationSteps: ['Control library definition', 'Policy mapping to workflows', 'Evidence automation rollout', 'Audit simulation and readiness review'],
    securityAndScale: ['Access segregation support', 'Control version tracking', 'Enterprise governance dashboards'],
    faqs: [
      { question: 'Does this reduce audit preparation effort?', answer: 'Yes, automated evidence capture significantly lowers manual audit preparation cycles.' },
      { question: 'Can controls evolve over time?', answer: 'Yes, policies and control sets can be versioned and rolled out with governance approvals.' },
    ],
    ctaLabel: 'Plan Compliance Modernization',
  },
  'clinical-decision-support': {
    title: 'Clinical Decision Support',
    subtitle: 'Context-aware recommendation support for clinicians and pathologists handling complex diagnostic interpretation workflows.',
    heroImageUrl: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1579165466741-7f35e4755660?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Clinical Confidence with Explainable Intelligence',
    overviewText: 'This module delivers guidance aligned to clinical context and protocols, helping teams reduce variation and improve care-pathway consistency.',
    valuePoints: ['Protocol-linked recommendation logic', 'Case context aggregation', 'Risk flag generation', 'Explainable suggestion support'],
    solutionPillars: [
      { title: 'Integrated Clinical Workflows', description: 'Decision support is embedded in review pathways rather than managed separately.' },
      { title: 'Speaking Your Language', description: 'Recommendations align to clinician and pathologist reasoning frameworks.' },
      { title: 'Working in Partnership', description: 'Clinical teams participate in design, tuning, and governance of recommendation rules.' },
    ],
    implementationSteps: ['Guideline and pathway mapping', 'Clinical rule validation', 'Pilot with selected specialties', 'Scale with governance oversight'],
    securityAndScale: ['Patient context protection controls', 'Clinical decision traceability', 'Site-specific configuration support'],
    faqs: [
      { question: 'Are recommendations explainable?', answer: 'Yes, outputs include context and rule rationale to support safe interpretation.' },
      { question: 'Can local protocols be configured?', answer: 'Yes, institution-specific pathways can be mapped and maintained.' },
    ],
    ctaLabel: 'Request Clinical Workflow Review',
  },
  'patient-portal': {
    title: 'Patient Portal',
    subtitle: 'Secure, patient-centric engagement platform for result access, status tracking, and communication transparency.',
    heroImageUrl: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Enhanced Patient Experience Through Digital Access',
    overviewText: 'Patient Portal extends diagnostics operations into a trusted digital interface for patients, improving communication and reducing support load.',
    valuePoints: ['Report and status access', 'Patient communication workflows', 'Consent visibility', 'Secure notification channels'],
    solutionPillars: [
      { title: 'Integrated Patient Journeys', description: 'Status, report, and follow-up communication are presented in one coherent experience.' },
      { title: 'Speaking Your Language', description: 'Patient-facing communication can be tailored to regional and audience needs.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Privacy-first controls and flexible configuration support diverse care models.' },
    ],
    implementationSteps: ['Portal journey design', 'Identity and access integration', 'Result communication setup', 'Adoption and support enablement'],
    securityAndScale: ['Identity verification controls', 'Privacy and consent enforcement', 'Scalable communication infrastructure'],
    faqs: [
      { question: 'Can communication channels be customized?', answer: 'Yes, notifications can be configured by channel preference and policy rules.' },
      { question: 'Does it work for multi-location service models?', answer: 'Yes, patients can access relevant records across supported locations.' },
    ],
    ctaLabel: 'Design Patient Experience Program',
  },
  'telemedicine-integration': {
    title: 'Telemedicine Integration',
    subtitle: 'Virtual care interoperability connecting diagnostics outputs to consult, referral, and care coordination pathways.',
    heroImageUrl: 'https://images.unsplash.com/photo-1584432810601-6c7f27d2362b?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1588776814546-ec7e6f4bb4b5?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Connected Care Across Physical and Virtual Services',
    overviewText: 'Telemedicine Integration ensures clinicians receive contextual diagnostics data in time for consultation and referral decisions.',
    valuePoints: ['Consult-ready diagnostics context', 'Referral handoff workflows', 'Cross-provider data exchange', 'Care continuity support'],
    solutionPillars: [
      { title: 'Integrated Care Ecosystems', description: 'Diagnostic information flows across provider boundaries with governance controls.' },
      { title: 'Working in Partnership', description: 'Deployment aligns telehealth operations and diagnostics teams around shared outcomes.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Secure exchange architecture supports dynamic provider networks.' },
    ],
    implementationSteps: ['Care pathway mapping', 'Connector and API setup', 'Referral and consult validation', 'Network rollout with monitoring'],
    securityAndScale: ['Provider-level access policies', 'Interoperability audit history', 'Scalable multi-provider integration'],
    faqs: [
      { question: 'Can multiple telehealth platforms be supported?', answer: 'Yes, connector architecture supports multi-platform virtual care environments.' },
      { question: 'How is continuity tracked?', answer: 'Referral states and consult handoff timelines are tracked for operational oversight.' },
    ],
    ctaLabel: 'Connect Virtual Care Workflows',
  },
  'api-suite': {
    title: 'ForMedrix API Suite',
    subtitle: 'Developer-grade APIs and event interfaces for building healthcare applications, automations, and partner integrations.',
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Flexible Innovation Platform for Healthcare Builders',
    overviewText: 'The API Suite enables engineering teams to extend diagnostics intelligence into new products and operational services.',
    valuePoints: ['Versioned API endpoints', 'Webhook event channels', 'Token and access controls', 'Developer sandbox support'],
    solutionPillars: [
      { title: 'Integrated Innovation Framework', description: 'APIs and events provide stable foundations for custom product development.' },
      { title: 'Working in Partnership', description: 'Integration teams and product engineers collaborate through defined launch and governance stages.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Secure-by-design controls protect data access while enabling rapid iteration.' },
    ],
    implementationSteps: ['Use-case and API contract definition', 'Auth and access policy setup', 'Integration testing and certification', 'Production rollout with observability'],
    securityAndScale: ['Token lifecycle governance', 'Per-consumer access scopes', 'Scalable event delivery and API throughput'],
    faqs: [
      { question: 'Is long-term compatibility supported?', answer: 'Yes, versioning strategy supports stable consumer integration over time.' },
      { question: 'Can partner onboarding be standardized?', answer: 'Yes, onboarding workflows include documentation, sandbox testing, and certification gates.' },
    ],
    ctaLabel: 'Start API Integration Program',
  },
  'mobile-diagnostics-app': {
    title: 'Mobile Diagnostics App',
    subtitle: 'Field-ready mobile operations for sample collection, status visibility, and escalation workflows in decentralized care models.',
    heroImageUrl: 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&w=1600&q=80',
    careImageUrl: 'https://images.unsplash.com/photo-1578496479531-32fba0f84d7c?auto=format&fit=crop&w=1400&q=80',
    labImageUrl: 'https://images.unsplash.com/photo-1600959907703-125ba1374a12?auto=format&fit=crop&w=1400&q=80',
    overviewTitle: 'Operational Mobility for Distributed Diagnostic Services',
    overviewText: 'Mobile Diagnostics App enables teams to capture, validate, and synchronize field diagnostics data securely, even in low-connectivity conditions.',
    valuePoints: ['Offline-first sample capture', 'Field status and escalation workflows', 'Media and metadata logging', 'Secure synchronization controls'],
    solutionPillars: [
      { title: 'Integrated Field-to-Lab Workflows', description: 'Mobile operations are linked to central systems for continuity and visibility.' },
      { title: 'Speaking Your Language', description: 'Workflows are tailored to field teams, not desktop-only process assumptions.' },
      { title: 'Trusted Security, Flexible Solutions', description: 'Secure mobile controls and role-based access protect data in distributed operations.' },
    ],
    implementationSteps: ['Field workflow mapping', 'Device and policy configuration', 'Pilot in target regions', 'Scale with supervision dashboards'],
    securityAndScale: ['Device access controls', 'Secure offline data handling', 'Scalable fleet and user management'],
    faqs: [
      { question: 'Can work continue without network coverage?', answer: 'Yes, offline capture and deferred sync are supported with audit tracking.' },
      { question: 'Can supervisors monitor distributed teams?', answer: 'Yes, field activity and escalation status are visible through centralized dashboards.' },
    ],
    ctaLabel: 'Plan Mobile Field Deployment',
  },
}
